<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<ProjectReference Include="..\Arklight.Game\Arklight.Game.csproj" />
		<PackageReference Include="Arklight-Freetype6" Version="1.0.11" />
		<PackageReference Include="Arklight-OpenAL-CS" Version="1.0.22" />
		<PackageReference Include="Arklight-SDL2-CS" Version="1.0.43" />
	</ItemGroup>
	<ItemGroup>
		<Content Include="Arklight.Platforms.Default.dll.config" Condition="'$(TargetPlatform)' != 'win-x64'">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
</Project>

