blank_issues_enabled: false
contact_links:
  - name: Frequently Asked Questions
    url: https://github.com/Arklight/Arklight/wiki/FAQ#frequently-asked-questions
    about: Explanations for common problems and questions.
  - name: Arklight Forum
    url: https://forum.Arklight.net/
    about: Please ask questions about modding here.
  - name: Arklight Discord server
    url: https://discord.Arklight.net/
    about: Join the community Discord server for community discussion and support.
  - name: Arklight IRC Channel
    url: https://web.libera.chat/#Arklight
    about: Join our development IRC channel on Libera for discussion of development topics.

