<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Arklight.Game\Arklight.Game.csproj" />
	</ItemGroup>
	<ItemGroup>
		<TrimmerRootAssembly Include="mscorlib" />
		<TrimmerRootAssembly Include="netstandard" />
		<TrimmerRootAssembly Include="System.IO.Pipes" />
	</ItemGroup>
</Project>

