<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<IsPublishable Condition="'$(CopyD2kDll)' == 'False'">false</IsPublishable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Arklight.Game\Arklight.Game.csproj">
			<Private>False</Private>
		</ProjectReference>
		<ProjectReference Include="..\Arklight.Mods.Common\Arklight.Mods.Common.csproj">
			<Private>False</Private>
		</ProjectReference>
	</ItemGroup>
</Project>

